# Each new term in the Fibonacci sequence
# is generated by adding the previous two
# terms. By starting with 1 and 2, the
# first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci
# sequence whose values do not exceed four
# million, find the sum of the even-valued terms.

fib1 = 1
fib2 = 2
sumEven = fib2
while (fib1 < 4000000) or (fib2 < 4000000) :
    if fib1 < fib2 :
        fib1 += fib2
        if fib1 % 2 == 0 :
            sumEven += fib1
    else :
        fib2 += fib1
        if fib2 % 2 == 0 :
            sumEven += fib2
print(sumEven)

# def fib(n):
#    a,b, c = 1,1,0
#    while a < n:
#        a, b = b, a+b
#        if a % 2 == 0:
#            c += a
#    return c
# fib(4000000)
